chore(iOS): update for Titanium 10.0.1
appcelerator/hyperloop-examples pull request #90
Opened 2021-05-21 05:10 UTC by jquick-axway

**Summary:**
- Replaced usage of getter/setter property methods.
- Replaced usage of deprecated `2DMatrix` with `Matrix2D`.
- Removed usage of deprecated `UILocalNotification`.
- Removed unused imports.
- Fixed JS code indentation.

**Note:**
This app will crash on startup on iOS due to a Titanium 10.0.0 regression with the `Hyperloop.defineClass()` method. Will be fixed by the following PR to be fixed in Titanium 10.0.1.
https://github.com/appcelerator/titanium_mobile/pull/12829

2021-05-24 09:16 UTC, ewanharris requested changes
Tested across iOS (using appcelerator/titanium_mobile/pull/12829) and Android, looks good!

Just one comment on the `ios/gravity` example where it looks like the import has changed

2021-05-24 09:22 UTC, ewanharris commented on app/controllers/ios/gravity.js
>  import { AVAudioPlayer } from 'AVFoundation';
Figured it just made more sense to push this to your branch seeing as I had it checked out and edited

2021-05-24 09:22 UTC, ewanharris approved these changes
Changing to approval

2021-05-24 18:40 UTC, jquick-axway commented on app/controllers/ios/gravity.js
>  import { AVAudioPlayer } from 'AVFoundation';
Per what we discussed, this looks like a breaking-change Apple made in the 14.5 iOS SDK. Changing the import from `AVFoundation` to `AVFAudio` will break for anyone using 14.4 (like me). But we need to move forward and make this change. Thanks Ewan.

2021-05-26 17:13 UTC, lokeshchdhry commented
FR Passed.
Checked with 10.0.1 SDK

2021-06-17 17:58 UTC, merged